##################################
# Backend & general settings
##################################

backend = "xrender";          #"xrender" | "glx"
vsync = true;

##################################
# Fading
##################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

##################################
# Shadows
##################################

shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.6;

wintypes:
{
  dock = { shadow = false; };      # don't shadow status bar
  dnd  = { shadow = false; };
  tooltip = { fade = true; shadow = true; };
};

##################################
# Transparency (optional eye candy)
##################################

inactive-opacity = 0.98;
frame-opacity = 1.0;

opacity-rule = [
  # Example: slightly transparent terminals
  "95:class_g = 'st-256color'"
];
